### ISSUE TITLE
配置M3DB后transfer正常启动，但是端口监听失效

### ISSUE THREAD

**Issue by JamesJoe-C** [didi/nightingale#617]
改M3DB后，transfer启动卡在这里：

`{"level":"info","ts":1615712676.6585393,"msg":"waiting for dynamic topology initialization, if this takes a long time, make sure that a topology/placement is configured"}`

transfer配置如下：
```
backend:
  datasource: "m3db"
  m3db:
    enabled: true
    name: "m3db"
    namespace: "default"
    seriesLimit: 0
    docsLimit: 0
    daysLimit: 7                               # max query time
    # https://m3db.github.io/m3/m3db/architecture/consistencylevels/
    writeConsistencyLevel: "majority"          # one|majority|all
    readConsistencyLevel: "unstrict_majority"  # one|unstrict_majority|majority|all
    config:
      service:
        # KV environment, zone, and service from which to write/read KV data (placement
        # and configuration). Leave these as the default values unless you know what
        # you're doing.
        env: default_env
        zone: embedded
        service: m3db
        etcdClusters:
          - zone: embedded
            endpoints:
              - 127.0.0.1:2379
            #tls:
            #  caCrtPath: /etc/etcd/certs/ca.pem
            #  crtPath: /etc/etcd/certs/etcd-client.pem
            #  keyPath: /etc/etcd/certs/etcd-client-key.pem
  tsdb:
    enabled: false
    name: "tsdb"
    cluster:
      tsdb01: 127.0.0.1:8011
  influxdb:
    enabled: false
    username: "influx"
    password: "admin123"
    precision: "s"
    database: "n9e"
    address: "http://127.0.0.1:8086"
  opentsdb:
    enabled: false
    address: "127.0.0.1:4242"
  kafka:
    enabled: false
    brokersPeers: "192.168.1.1:9092,192.168.1.2:9092"
    topic: "n9e"
logger:
  dir: logs/transfer
  level: INFO
  keepHours: 24
```
